Feature/add authorization
Leblyad/InnoClinic.AuthorizationAPI pull request #1
Opened 2022-11-18 10:46 UTC by Leblyad

2022-11-21 12:09 UTC, Leblyad commented
In this api each user has only one role.

2022-11-21 16:05 UTC, kseniya-kalita requested changes
Good work! Please review and resolve comments to have your code better. After that ping me and I'll review it one more time.

2022-11-21 16:05 UTC, kseniya-kalita commented on AuthorizationAPI/Presentation/Controllers/AuthenticationController.cs
> +        /// Creates a new user
Nice idea to have comments, like it! Please add also possible returned status cods. And add the possibility to view your comment in swagger.

2022-11-21 16:05 UTC, kseniya-kalita commented on AuthorizationAPI/Application/Serrvices.Abstractions/IAccountService.cs
> +namespace AuthorizationAPI.Application.Serrvices.Abstractions
And place this folder inside Services

2022-11-22 12:27 UTC, Leblyad commented on AuthorizationAPI/Infrastructure/Repository/AuthenticationDbContext.cs
> +
Sorry, i tried

2022-11-23 08:26 UTC, Leblyad commented on AuthorizationAPI/Presentation/Controllers/AuthenticationController.cs
> +        /// <param name="login"></param>
Username, i renamed it.

2022-11-23 08:28 UTC, Leblyad commented on AuthorizationAPI/Application/Services/AccountService.cs
> +                    throw new Exception("Role not exists");
Now i changed approach.

2022-11-23 08:38 UTC, Leblyad commented on AuthorizationAPI/Core/Entities/Models/AuthorizationDTO/AuthenticatedUserInfo.cs
> +        public IList<string> UserRoles { get; set; }
No, just one. Resolve it.

2022-11-23 09:19 UTC, Leblyad commented on AuthorizationAPI/Presentation/Controllers/AuthenticationController.cs
> +        /// Creates a new user
Done.

2022-11-24 17:04 UTC, kseniya-kalita approved these changes
Great job! Please resolve these small changes and merge without resending this PR to me

2022-11-24 17:04 UTC, kseniya-kalita commented on InnoClinic.AuthorizationAPI/appsettings.json
> +    "sqlConnection": "server=.\\SQLEXPRESS; database=Authorization; Integrated Security=true"
One last point: please add 'Db' ending to your database name :)

2022-11-25 08:36 UTC, merged